/**
 * Copyright (c) 2022, Jason He. All rights reserved.
 */

package com.github.hetianyi.plugin.sample.model.form;

import com.github.hetianyi.boot.ready.common.Convertible;
import com.github.hetianyi.boot.ready.model.http.Pageable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * 查询示例请求表单
 * 
 * <br><br>
 * This class is automatically generated by
 * <a href="https://github.com/hetianyi/code-generator-plugin">code-generator-plugin</a>.
 * 
 * @author Jason He
 */
@ApiModel(description = "示例请求表单")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class QueryExampleForm extends Pageable implements Convertible<QueryExampleForm> {

    /** 用户ID */
    @ApiModelProperty("用户ID")
    private String id;

    /** 用户名 */
    @ApiModelProperty("用户名")
    private String username;

    /** 昵称 */
    @ApiModelProperty("昵称")
    private String nickname;

    /** 起始创建时间 */
    @ApiModelProperty("起始创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdTimeStart;

    /** 截止创建时间 */
    @ApiModelProperty("截止创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdTimeEnd;

    /** 起始修改时间 */
    @ApiModelProperty("起始修改时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatedTimeStart;

    /** 截止修改时间 */
    @ApiModelProperty("截止修改时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatedTimeEnd;
}