/**
 * Copyright (c) 2022, Jason He. All rights reserved.
 */

package com.github.hetianyi.plugin.sample.model.form;

import com.github.hetianyi.boot.ready.common.Convertible;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 更新示例请求表单
 * 
 * <br><br>
 * This class is automatically generated by
 * <a href="https://github.com/hetianyi/code-generator-plugin">code-generator-plugin</a>.
 * 
 * @author Jason He
 */
@ApiModel(description = "更新示例请求表单")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class UpdateExampleForm implements Convertible<UpdateExampleForm> {

    /** 用户ID */
    @ApiModelProperty("用户ID")
    private String id;

    /** 用户名 */
    @ApiModelProperty("用户名")
    private String username;

    /** 昵称 */
    @ApiModelProperty("昵称")
    private String nickname;
}