/**
 * Copyright (c) 2022, Jason He. All rights reserved.
 */

package com.github.hetianyi.plugin.sample.model.form;

import com.github.hetianyi.boot.ready.common.Convertible;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 创建示例请求单
 * 
 * <br><br>
 * This class is automatically generated by
 * <a href="https://github.com/hetianyi/code-generator-plugin">code-generator-plugin</a>.
 * 
 * @author Jason He
 */
@ApiModel(description = "创建示例请求表单")
@NoArgsConstructor
@Builder
@AllArgsConstructor
@Data
public class CreateExampleForm implements Convertible<CreateExampleForm> {

    /** 示例名 */
    @ApiModelProperty("示例名")
    private String username;

    /** 昵称 */
    @ApiModelProperty("昵称")
    private String nickname;
}