/**
 * Copyright (c) 1994, 2013, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package com.github.hetianyi.plugin.sample.model.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.github.hetianyi.boot.ready.common.Convertible;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 示例表
 * 
 * <br><br>
 * This class is automatically generated by
 * <a href="https://github.com/hetianyi/code-generator-plugin">code-generator-plugin</a>.
 * 
 * @author Jason He
 */
@ApiModel(description = "示例表")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ExampleVO implements Convertible<ExampleVO> {

    /** 示例ID */
    @ApiModelProperty("示例ID")
    private String id;

    /** 示例名 */
    @ApiModelProperty("示例名")
    private String username;

    /** 昵称 */
    @ApiModelProperty("昵称")
    private String nickname;

    /** 创建时间 */
    @ApiModelProperty("创建时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdTime;

    /** 修改时间 */
    @ApiModelProperty("修改时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatedTime;
}